"""SymCC's check of the Cedar exact study's equivalence verdicts.

Protocol: `docs/CEDAR_SYMCC_CROSSCHECK_PROTOCOL.md`, whose hash is fixed below, as is the hash of
the schema list it was registered on (`docs/cedar-schema-candidates-v1.json`); the script
refuses to run on the population unless both files are the ones committed before it ran.

The Cedar exact study (`cedar_exact_study.py`) calls a mutant equivalent when no cell of its
file's witness space separates it from the file. Here SymCC, Cedar's symbolic compiler, is
asked the same question under the schema the file's own authors wrote, one request environment
at a time, through the `cedar symcc equivalent` command of `cedar-policy-cli` with the cvc5
solver. Every mutant is the study's own, regenerated by the study's code with its seed, and
every counterexample SymCC prints is parsed and decided again by the study's engine, cedarpy,
through the study's evaluation function. Only a counterexample the engine confirms refutes an
equivalent verdict; a verified equivalence holds only for the requests the schema admits.

`cedarpy` must be installed (`pip install cedarpy==4.12.1`), and the Cedar CLI's experimental
build and cvc5 must be on hand; the protocol names the builds and their digests.

Usage:
    python scripts/cedar_symcc_crosscheck.py study --cedar PATH/TO/cedar --cvc5 PATH/TO/cvc5 \\
        --cache DIR --workers 8 --partial PARTIAL.jsonl --json docs/cedar-symcc-crosscheck-v1.json
"""

from __future__ import annotations

import argparse
import concurrent.futures
import hashlib
import importlib.metadata
import importlib.util
import json
import multiprocessing
import platform
import random
import subprocess
import sys
import tempfile
from collections import Counter
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
PROTOCOL = DOCS / "CEDAR_SYMCC_CROSSCHECK_PROTOCOL.md"
PROTOCOL_SHA256 = "111830694f0a3a0e12034acebe147091cbe70ab57a491a282611dc3882caa319"
CANDIDATES = DOCS / "cedar-schema-candidates-v1.json"
CANDIDATES_SHA256 = "e7b0954e645117a2e21dd6fff65f196b31c715b144fd940564e88049f0720436"
DEVELOPMENT = "Anumehajain78/promptfence/backend/policies/forbid-support-delete.cedar"
WALL_CLOCK = 600
SOLVER_LIMIT_MS = 60_000
DEVIATIONS = [
    "A first run of the population, with the instrument as committed at b4cbfee, read every "
    "counterexample except those holding a datetime, which the command prints as an offset "
    'from a date, `(datetime("1970-01-01")).offset(duration("0ms"))`. Its 25 such '
    "counterexamples, all on live mutants of two files, went unreplayed, and those mutants were "
    "then labelled by their environments' results alone. The parser now reads calls and method "
    "calls and passes them on in Cedar's JSON form for the engine to evaluate, a live mutant "
    "whose counterexamples the engine did not confirm has a class of its own, and the whole "
    "population was run again. The first run found, of 173 equivalent verdicts, none refuted, "
    "161 verified in every environment, 10 partly checked and 2 unchecked; of 830 live "
    "verdicts, 722 confirmed live and 72 equivalent in every usable environment.",
]
VERIFIED = "Policy sets are equivalent: VERIFIED"
DOES_NOT_HOLD = "Policy sets are equivalent: DOES NOT HOLD"
EQUIVALENT_CLASSES = (
    "refuted",
    "not refuted, every environment verified",
    "not refuted, partly checked",
    "unchecked",
)
LIVE_CLASSES = (
    "live under the schema",
    "equivalent under the schema",
    "counterexample not confirmed",
    "equivalent where checked",
    "unchecked",
)


def _load(name: str) -> Any:
    if name in sys.modules:
        return sys.modules[name]
    specification = importlib.util.spec_from_file_location(name, ROOT / "scripts" / f"{name}.py")
    assert specification and specification.loader
    module = importlib.util.module_from_spec(specification)
    sys.modules[name] = module
    specification.loader.exec_module(module)
    return module


def _lf_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes().replace(b"\r\n", b"\n")).hexdigest()


def require_registration() -> None:
    for path, fixed in ((PROTOCOL, PROTOCOL_SHA256), (CANDIDATES, CANDIDATES_SHA256)):
        found = _lf_sha256(path)
        if found != fixed:
            raise SystemExit(
                f"{path.name} hashes to {found}, not the {fixed} fixed before the study ran; "
                "a changed protocol or schema list is a different study, so this one refuses "
                "to run"
            )


# ---------------------------------------------------------------------------------------
# Reading a counterexample
# ---------------------------------------------------------------------------------------


class Unreadable(ValueError):
    """Counterexample text this parser cannot read; the counterexample is kept unreplayed."""


_ESCAPES = {"n": "\n", "r": "\r", "t": "\t", "0": "\0", "\\": "\\", '"': '"', "'": "'"}


class _Reader:
    """A cursor over the environment SymCC prints (`cedar_policy_symcc::Env`'s Display).

    Values are printed in Cedar's literal syntax with Rust's `escape_debug` for strings:
    entity references as `Type::"id"`, extension values as calls such as `decimal("1.0")`, or
    `(datetime("1970-01-01")).offset(duration("0ms"))` for a datetime, sets in brackets, and
    records in braces with identifier or string keys. A call is passed on in Cedar's JSON form
    for extension values, so the engine, not this parser, computes what it denotes.
    """

    def __init__(self, text: str) -> None:
        self.text = text
        self.at = 0

    def ahead(self, literal: str) -> bool:
        return self.text.startswith(literal, self.at)

    def expect(self, literal: str) -> None:
        if not self.ahead(literal):
            raise Unreadable(f"expected {literal!r} at {self.text[self.at : self.at + 40]!r}")
        self.at += len(literal)

    def string(self) -> str:
        self.expect('"')
        out: list[str] = []
        while True:
            if self.at >= len(self.text):
                raise Unreadable("unterminated string")
            char = self.text[self.at]
            self.at += 1
            if char == '"':
                return "".join(out)
            if char != "\\":
                out.append(char)
                continue
            code = self.text[self.at : self.at + 1]
            self.at += 1
            if code in _ESCAPES:
                out.append(_ESCAPES[code])
            elif code == "u" and self.ahead("{"):
                end = self.text.index("}", self.at)
                out.append(chr(int(self.text[self.at + 1 : end], 16)))
                self.at = end + 1
            else:
                raise Unreadable(f"unknown escape \\{code}")

    def identifier(self) -> str:
        start = self.at
        while self.at < len(self.text) and (
            self.text[self.at].isalnum() or self.text[self.at] == "_"
        ):
            self.at += 1
        if start == self.at or self.text[start].isdigit():
            raise Unreadable(f"expected a name at {self.text[start : start + 40]!r}")
        return self.text[start : self.at]

    def uid(self) -> tuple[str, str]:
        path = [self.identifier()]
        while True:
            self.expect("::")
            if self.ahead('"'):
                return "::".join(path), self.string()
            path.append(self.identifier())

    def arguments(self) -> list[Any]:
        self.expect("(")
        found: list[Any] = []
        while not self.ahead(")"):
            if found:
                self.expect(", ")
            found.append(self.value())
        self.expect(")")
        return found

    def methods(self, receiver: Any) -> Any:
        """`.name(arguments)` calls on a value, as Cedar's JSON writes a call of `name`."""

        while self.ahead("."):
            self.expect(".")
            name = self.identifier()
            receiver = {"__extn": {"fn": name, "args": [receiver, *self.arguments()]}}
        return receiver

    def value(self) -> Any:
        if self.ahead("<unknown>"):
            raise Unreadable("a value SymCC could not concretise")
        if self.ahead("("):
            self.expect("(")
            inner = self.value()
            self.expect(")")
            return self.methods(inner)
        if self.ahead('"'):
            return self.string()
        if self.ahead("["):
            self.expect("[")
            items: list[Any] = []
            while not self.ahead("]"):
                if items:
                    self.expect(", ")
                items.append(self.value())
            self.expect("]")
            return items
        if self.ahead("{"):
            self.expect("{")
            record: dict[str, Any] = {}
            while not self.ahead("}"):
                if record:
                    self.expect(", ")
                key = self.string() if self.ahead('"') else self.identifier()
                self.expect(": ")
                record[key] = self.value()
            self.expect("}")
            return record
        if self.ahead("-") or self.text[self.at : self.at + 1].isdigit():
            start = self.at
            self.at += 1
            while self.text[self.at : self.at + 1].isdigit():
                self.at += 1
            return int(self.text[start : self.at])
        path = [self.identifier()]
        while self.ahead("::"):
            self.expect("::")
            if self.ahead('"'):
                return {"__entity": {"type": "::".join(path), "id": self.string()}}
            path.append(self.identifier())
        if self.ahead("("):
            found = self.arguments()
            name = "::".join(path)
            call = {"fn": name, "arg": found[0]} if len(found) == 1 else {"fn": name, "args": found}
            return self.methods({"__extn": call})
        if path in (["true"], ["false"]):
            return path == ["true"]
        raise Unreadable(f"unknown value {'::'.join(path)!r}")

    def attributes(self) -> dict[str, Any]:
        """`    key: value,` lines up to the closing `  }`; keys are printed as they are."""

        found: dict[str, Any] = {}
        while not self.ahead("  }"):
            self.expect("    ")
            end = self.text.find(": ", self.at)
            if end < 0:
                raise Unreadable("an attribute without a value")
            key = self.text[self.at : end]
            self.at = end + 2
            found[key] = self.value()
            self.expect(",\n")
        self.expect("  }")
        return found


def _cedar_uid(uid: tuple[str, str]) -> str:
    escaped = "".join(
        "\\\\"
        if c == "\\"
        else '\\"'
        if c == '"'
        else c
        if c.isprintable()
        else f"\\u{{{ord(c):x}}}"
        for c in uid[1]
    )
    return f'{uid[0]}::"{escaped}"'


def parse_counterexample(text: str) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    """The request and entity store a `cedar symcc` counterexample describes, as cedarpy reads
    them: the request's entities as `Type::"id"` strings, values in Cedar's JSON form."""

    marker = "Counterexample found:\n"
    text = text.replace("\r\n", "\n")
    if marker not in text:
        raise Unreadable("no counterexample in the output")
    reader = _Reader(text.split(marker, 1)[1])
    roles: dict[str, tuple[str, str]] = {}
    for role, lead in (
        ("principal", "principal: "),
        ("action", ", action: "),
        ("resource", ", resource: "),
    ):
        reader.expect(lead)
        roles[role] = reader.uid()
    context: dict[str, Any] = {}
    if reader.ahead("\ncontext: "):
        reader.expect("\ncontext: ")
        context = reader.value()
        if not isinstance(context, dict):
            raise Unreadable("a context that is not a record")
    entities: list[dict[str, Any]] = []
    if reader.ahead("\nentities: [\n"):
        reader.expect("\nentities: [\n")
        while not reader.ahead("]"):
            reader.expect("  ")
            uid = reader.uid()
            parents: list[tuple[str, str]] = []
            if reader.ahead(" in ["):
                reader.expect(" in [")
                while not reader.ahead("]"):
                    if parents:
                        reader.expect(", ")
                    parents.append(reader.uid())
                reader.expect("]")
            attributes: dict[str, Any] = {}
            tags: dict[str, Any] = {}
            if reader.ahead(" {\n"):
                reader.expect(" {\n")
                attributes = reader.attributes()
            if reader.ahead(" tags {\n"):
                reader.expect(" tags {\n")
                tags = reader.attributes()
            reader.expect(",\n")
            entity: dict[str, Any] = {
                "uid": {"__entity": {"type": uid[0], "id": uid[1]}},
                "attrs": attributes,
                "parents": [{"__entity": {"type": t, "id": i}} for t, i in parents],
            }
            if tags:
                entity["tags"] = tags
            entities.append(entity)
        reader.expect("]")
    request = {role: _cedar_uid(uid) for role, uid in roles.items()}
    request["context"] = context
    return request, entities


# ---------------------------------------------------------------------------------------
# SymCC and the engine
# ---------------------------------------------------------------------------------------


def outcome(returncode: int, stdout: str, stderr: str) -> str:
    """One environment's result, as the protocol names them."""

    if returncode == 0 and VERIFIED in stdout:
        return "verified"
    if returncode == 0 and DOES_NOT_HOLD in stdout:
        return "counterexample"
    if "Failed to compile policy set 2" in stderr:
        return "mutant does not compile"
    if "Failed to compile policy set 1" in stderr:
        return "file does not compile"
    return "no answer"


def symcc(
    cedar: str,
    cvc5: str,
    environment: list[str],
    schema: Path,
    schema_format: str,
    first: Path,
    first_format: str,
    second: Path,
) -> tuple[str, str]:
    principal, action, resource = environment
    command = [
        cedar,
        "symcc",
        "--cvc5-path",
        cvc5,
        "--principal-type",
        principal,
        "--action",
        action,
        "--resource-type",
        resource,
        "--schema",
        str(schema),
        "--schema-format",
        schema_format,
        "--counterexample",
        "equivalent",
        "--policies1",
        str(first),
        "--policies1-format",
        first_format,
        "--policies2",
        str(second),
        "--policies2-format",
        "json",
    ]
    try:
        done = subprocess.run(
            command,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=WALL_CLOCK,
            check=False,
        )
    except subprocess.TimeoutExpired:
        return "wall-clock limit", ""
    result = outcome(done.returncode, done.stdout, done.stderr)
    detail = done.stdout if result == "counterexample" else done.stderr.strip()[-600:]
    return result, detail if result != "verified" else ""


def replay(
    original: dict[str, Any], mutant: dict[str, Any], text: str
) -> tuple[str, dict[str, Any]]:
    """Whether the engine confirms a counterexample: `confirmed`, `unconfirmed` or `unreplayed`."""

    ces = _load("cedar_exact_study")
    cedarpy, _ = ces._cedar()
    try:
        request, entities = parse_counterexample(text)
    except (Unreadable, ValueError) as error:
        return "unreplayed", {"why": str(error)[:200]}
    try:
        batches = ces.batches_of([(request, entities)])
        decided = [
            ces.evaluate(cedarpy.PolicySet.from_json_str(json.dumps(est)), batches, 1)[0][0]
            for est in (original, mutant)
        ]
    except Exception as error:  # noqa: BLE001 - the engine refusing the request is recorded
        return "unreplayed", {"why": f"the engine refused it: {str(error)[:200]}"}
    detail = {
        "file": decided[0],
        "mutant": decided[1],
        "principal_is_resource": request["principal"] == request["resource"],
    }
    return ("confirmed" if decided[0] != decided[1] else "unconfirmed"), detail


def classify(study_verdict: str, results: list[str], replays: list[str]) -> str:
    """A verdict's class from its environments' results and its counterexamples' replays.

    The protocol defines the four classes of an equivalent verdict and the first two of a live
    one. A live verdict in neither is placed by what kept it out: a counterexample the engine
    did not confirm, or an environment without an answer.
    """

    verified = results.count("verified")
    if study_verdict == "equivalent":
        if "confirmed" in replays:
            return "refuted"
        if results and verified == len(results):
            return "not refuted, every environment verified"
        return "not refuted, partly checked" if verified else "unchecked"
    if "confirmed" in replays:
        return "live under the schema"
    if results and verified == len(results):
        return "equivalent under the schema"
    if replays:
        return "counterexample not confirmed"
    return "equivalent where checked" if verified else "unchecked"


def _operator(name: str) -> str:
    if name.startswith("literal_to_"):
        return "literal_to"
    return name.split("[", 1)[0].split("@", 1)[0].rstrip("0123456789")


def check_file(task: dict[str, Any]) -> dict[str, Any]:
    """Reproduce one file's verdicts, run the control, and check every mutant."""

    ces = _load("cedar_exact_study")
    subject = task["subject"]
    est = json.loads(task["est"])
    record: dict[str, Any] = {
        "subject": subject,
        "development": subject == DEVELOPMENT,
        "schema": {"path": task["schema_path"], "kind": task["schema_kind"]},
        "environments": len(task["environments"]),
    }
    analysis = ces.analyse_file(est, generator=random.Random(f"{ces.SEED}:{subject}"))
    statuses = Counter(m["status"] for m in analysis.get("mutants", []))
    record["reproduced"] = dict(sorted(statuses.items()))
    if analysis.get("status") != "scored" or dict(statuses) != task["expected"]:
        record["status"] = "verdicts not reproduced"
        return record
    found = ces.observables_of(est)
    mutants = list(ces.mutants_of(est, found))
    names = [m["mutant"] for m in analysis["mutants"]]
    if [name for name, _ in mutants] != names:
        record["status"] = "verdicts not reproduced"
        return record

    with tempfile.TemporaryDirectory() as directory:
        root = Path(directory)
        text, original, schema = root / "file.cedar", root / "file.json", root / "schema"
        text.write_bytes(task["text"].encode("utf-8"))
        original.write_text(json.dumps(est), encoding="utf-8")
        schema.write_text(task["schema"], encoding="utf-8")
        tools = (task["cedar"], task["cvc5"])

        control: Counter[str] = Counter()
        usable: list[int] = []
        for index, environment in enumerate(task["environments"]):
            result, _ = symcc(
                *tools, environment, schema, task["schema_format"], text, "cedar", original
            )
            control[result] += 1
            if result == "verified":
                usable.append(index)
        record["control"] = dict(sorted(control.items()))
        record["usable_environments"] = len(usable)
        if control.get("counterexample"):
            record["status"] = "JSON form not faithful"
            return record
        if not usable:
            record["status"] = "SymCC does not compile it"
            return record

        checked: list[dict[str, Any]] = []
        for (name, mutated), verdict in zip(mutants, analysis["mutants"], strict=True):
            if verdict["status"] not in ("equivalent", "live"):
                continue
            path = root / "mutant.json"
            path.write_text(json.dumps(mutated), encoding="utf-8")
            results: list[str] = []
            counterexamples: list[dict[str, Any]] = []
            confirmed = False
            for index in usable:
                result, detail = symcc(
                    *tools,
                    task["environments"][index],
                    schema,
                    task["schema_format"],
                    original,
                    "json",
                    path,
                )
                results.append(result)
                if result == "counterexample":
                    replayed, facts = replay(est, mutated, detail)
                    entry = {"environment": index, "replay": replayed, **facts}
                    if replayed != "confirmed" or verdict["status"] == "equivalent":
                        entry["text"] = detail
                    counterexamples.append(entry)
                    confirmed = confirmed or replayed == "confirmed"
                    if confirmed and verdict["status"] == "live":
                        break
            checked.append(
                {
                    "mutant": name,
                    "operator": _operator(name),
                    "study": verdict["status"],
                    "class": classify(
                        verdict["status"], results, [c["replay"] for c in counterexamples]
                    ),
                    "results": dict(sorted(Counter(results).items())),
                    "counterexamples": counterexamples,
                }
            )
        record["status"] = "checked"
        record["mutants"] = checked
    return record


# ---------------------------------------------------------------------------------------
# The study
# ---------------------------------------------------------------------------------------


def _file_text(entry: dict[str, str], cache: Path) -> str:
    """The file at its recorded digest, cached as the Cedar exact study caches it."""

    subject = f"{entry['repo']}/{entry['path']}"
    stored = cache / hashlib.sha256(subject.encode()).hexdigest()
    if not (stored.exists() and hashlib.sha256(stored.read_bytes()).hexdigest() == entry["sha256"]):
        content, status = _load("measure_third_party_policies").fetch_bytes(entry)
        if content is None or hashlib.sha256(content).hexdigest() != entry["sha256"]:
            raise SystemExit(f"{subject}: not available at its recorded digest ({status})")
        stored.parent.mkdir(parents=True, exist_ok=True)
        stored.write_bytes(content)
    return stored.read_bytes().decode("utf-8")


def _schema_text(listed: dict[str, Any], cache: Path) -> str:
    schema = listed["schema"]
    candidates = _load("cedar_schema_candidates")
    content = candidates.blob(
        listed["repo"], listed["commit"], schema["path"], schema["blob_sha1"], cache
    )
    if content is None or hashlib.sha256(content).hexdigest() != schema["sha256"]:
        raise SystemExit(f"{listed['subject']}: its schema is not available at its digest")
    return candidates.schema_source(content, schema["path"])[1]


def _tool(command: list[str], binary: str) -> dict[str, str]:
    done = subprocess.run(command, capture_output=True, text=True, check=False)
    resolved = Path(binary)
    return {
        "version": (done.stdout or done.stderr).strip().splitlines()[0],
        "sha256": hashlib.sha256(resolved.read_bytes()).hexdigest() if resolved.is_file() else "",
    }


def _share(numerator: int, denominator: int) -> float | None:
    return round(numerator / denominator, 6) if denominator else None


def summarise(records: list[dict[str, Any]]) -> dict[str, Any]:
    pooled = [r for r in records if not r["development"]]
    mutants = [m for r in pooled if r["status"] == "checked" for m in r["mutants"]]
    equivalent = [m for m in mutants if m["study"] == "equivalent"]
    live = [m for m in mutants if m["study"] == "live"]
    replays = Counter(c["replay"] for m in mutants for c in m["counterexamples"])
    refutations = [
        {
            "file": r["subject"],
            "mutant": m["mutant"],
            **{k: v for k, v in c.items() if k != "replay"},
        }
        for r in pooled
        if r["status"] == "checked"
        for m in r["mutants"]
        if m["class"] == "refuted"
        for c in m["counterexamples"]
        if c["replay"] == "confirmed"
    ]
    schema_equivalent = [m for m in live if m["class"] == "equivalent under the schema"]
    return {
        "files": dict(sorted(Counter(r["status"] for r in pooled).items())),
        "primary": {
            "equivalent_verdicts": len(equivalent),
            "classes": {
                c: sum(1 for m in equivalent if m["class"] == c) for c in EQUIVALENT_CLASSES
            },
            "refutations": refutations,
            "refutations_whose_principal_is_the_resource": sum(
                1 for r in refutations if r.get("principal_is_resource")
            ),
            "with_a_counterexample_the_engine_did_not_confirm": [
                {
                    "file": r["subject"],
                    "mutant": m["mutant"],
                    "replays": [c["replay"] for c in m["counterexamples"]],
                }
                for r in pooled
                if r["status"] == "checked"
                for m in r["mutants"]
                if m["study"] == "equivalent"
                and any(c["replay"] != "confirmed" for c in m["counterexamples"])
            ],
        },
        "secondary": {
            "live_verdicts": len(live),
            "classes": {c: sum(1 for m in live if m["class"] == c) for c in LIVE_CLASSES},
            "share_equivalent_under_the_schema": _share(len(schema_equivalent), len(live)),
            "equivalent_under_the_schema_by_operator": dict(
                sorted(Counter(m["operator"] for m in schema_equivalent).items())
            ),
            "live_by_operator": dict(sorted(Counter(m["operator"] for m in live).items())),
            "counterexamples": dict(sorted(replays.items())),
            "control": {r["subject"]: r.get("control") for r in pooled},
        },
    }


def study(
    cedar: str,
    cvc5: str,
    cache: Path,
    workers: int,
    partial: Path,
    only: list[str] | None = None,
) -> dict[str, Any]:
    require_registration()
    artifact = json.loads((DOCS / "cedar-suite-strategy-study-v1.json").read_text("utf-8"))
    engine = f"cedarpy {importlib.metadata.version('cedarpy')}"
    if engine != artifact["engine"]:
        raise SystemExit(f"the study's engine is {artifact['engine']}, this is {engine}")
    _, internal = _load("cedar_exact_study")._cedar()
    manifest = json.loads((DOCS / "third-party-sample-cedar-corpus-v1.json").read_text("utf-8"))
    index = {f"{entry['repo']}/{entry['path']}": entry for entry in manifest["files"]}
    listed = json.loads(CANDIDATES.read_text("utf-8"))
    done: dict[str, dict[str, Any]] = {}
    if partial.exists():
        for line in partial.read_text("utf-8").splitlines():
            if line.strip():
                record = json.loads(line)
                done[record["subject"]] = record
    tasks: list[dict[str, Any]] = []
    for entry in listed["files"]:
        if not entry["schema"] or entry["subject"] in done:
            continue
        if only and entry["subject"] not in only:
            continue
        text = _file_text(index[entry["subject"]], cache)
        expected = {k: v for k, v in artifact["files"][entry["subject"]]["mutants"].items() if v}
        tasks.append(
            {
                "subject": entry["subject"],
                "text": text,
                "est": internal.policies_to_json_str(text),
                "schema": _schema_text(entry, cache),
                "schema_format": entry["schema"]["format"],
                "schema_path": entry["schema"]["path"],
                "schema_kind": entry["schema"]["kind"],
                "environments": entry["environments"],
                "expected": expected,
                "cedar": cedar,
                "cvc5": cvc5,
            }
        )
    # Heaviest first, so the longest files do not start last.
    tasks.sort(key=lambda t: -len(t["environments"]) * sum(t["expected"].values()))
    context = multiprocessing.get_context("spawn")
    with (
        concurrent.futures.ProcessPoolExecutor(workers, mp_context=context) as pool,
        partial.open("a", encoding="utf-8") as sink,
    ):
        futures = [pool.submit(check_file, task) for task in tasks]
        for future in concurrent.futures.as_completed(futures):
            record = future.result()
            done[record["subject"]] = record
            sink.write(json.dumps(record) + "\n")
            sink.flush()
            print(f"{len(done)} {record['subject']}: {record['status']}", file=sys.stderr)

    records = [done[s] for s in sorted(done)]
    development = [r for r in records if r["development"]]
    return {
        "schema_version": "v1",
        "protocol_sha256": PROTOCOL_SHA256,
        "candidates_sha256": CANDIDATES_SHA256,
        "engine": engine,
        "seed": _load("cedar_exact_study").SEED,
        "tools": {
            "cedar": _tool([cedar, "--version"], cedar),
            "cvc5": _tool([cvc5, "--version"], cvc5),
            "platform": f"{platform.system()} {platform.machine()}",
        },
        "limits": {"wall_clock_seconds": WALL_CLOCK, "solver_ms_per_query": SOLVER_LIMIT_MS},
        "deviations": DEVIATIONS,
        "summary": summarise(records),
        "development": development,
        "files": [r for r in records if not r["development"]],
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    run = sub.add_parser("study")
    run.add_argument("--cedar", required=True)
    run.add_argument("--cvc5", required=True)
    run.add_argument("--cache", type=Path, required=True)
    run.add_argument("--workers", type=int, default=4)
    run.add_argument("--partial", type=Path, required=True)
    run.add_argument("--only", nargs="*")
    run.add_argument("--json", type=Path)
    args = parser.parse_args(argv)
    # Absolute paths: Windows does not resolve a relative executable path in the workers.
    cedar, cvc5 = (
        str(Path(tool).resolve()) if Path(tool).is_file() else tool
        for tool in (args.cedar, args.cvc5)
    )
    result = study(cedar, cvc5, args.cache, args.workers, args.partial, args.only)
    text = json.dumps(result, indent=1, ensure_ascii=False)
    if args.json:
        args.json.write_text(text + "\n", encoding="utf-8")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
