import TrustweaveLean.Basic
import TrustweaveLean.Quotient
import TrustweaveLean.Kill
import TrustweaveLean.Achievable
import TrustweaveLean.Patterns
import TrustweaveLean.PrefixChain
import TrustweaveLean.Undecidable
import TrustweaveLean.Counterexamples

/-!
# Axiom audit

`#print axioms` for every theorem stated in this development, followed by a build-time check
that fails the build if any theorem in the `TrustWeave` namespace, including the lemmas Lean
generates itself, depends on an axiom other than `propext`, `Classical.choice` and
`Quot.sound`. A placeholder for an unfinished proof would show up as an extra axiom, and
so would a proof by `native_decide`, so either fails the build here.

Run `lake env lean TrustweaveLean/Audit.lean` to see the output.
-/

-- Basic
#print axioms TrustWeave.guardSim_iff
#print axioms TrustWeave.Policy.sim_iff
#print axioms TrustWeave.Policy.sem_eq_combine_outcome
#print axioms TrustWeave.Suite.covers_iff

-- Quotient
#print axioms TrustWeave.Policy.cellOutcome_mk
#print axioms TrustWeave.Policy.cellOutcome_injective
#print axioms TrustWeave.Policy.card_cells_eq_card_achieved
#print axioms TrustWeave.Policy.finite_cells
#print axioms TrustWeave.Policy.card_cells_le
#print axioms TrustWeave.Policy.sem_eq_of_sim
#print axioms TrustWeave.Policy.sim_le_ker_sem
#print axioms TrustWeave.Policy.cellSem_mk
#print axioms TrustWeave.Policy.sim_eq_of_guard_eq
#print axioms TrustWeave.combining_rule_independence

-- Kill
#print axioms TrustWeave.kill_criterion
#print axioms TrustWeave.exact_kill_criterion
#print axioms TrustWeave.coverage_decides_score
#print axioms TrustWeave.setoid_iInf_iff
#print axioms TrustWeave.commonRefinement_iff
#print axioms TrustWeave.commonRefinement_eq_ker
#print axioms TrustWeave.finite_commonRefinement
#print axioms TrustWeave.coverage_decides_score_policies
#print axioms TrustWeave.semantic_mutants_sufficiency_general
#print axioms TrustWeave.semantic_mutants_necessity_general
#print axioms TrustWeave.semantic_mutants_general
#print axioms TrustWeave.semantic_mutants_sufficiency
#print axioms TrustWeave.semantic_mutants
#print axioms TrustWeave.semantic_mutants_constant_on_cells

-- Achievable
#print axioms TrustWeave.achievable_iff
#print axioms TrustWeave.achieves_witness
#print axioms TrustWeave.achievable_iff_purpose

-- Patterns
#print axioms TrustWeave.Pattern.dominates_iff_synDominates
#print axioms TrustWeave.achievable_iff_no_dominance

-- PrefixChain
#print axioms TrustWeave.prefixOutcome_mem
#print axioms TrustWeave.prefix_patterns_card_le

-- Undecidable
#print axioms TrustWeave.exists_haltsWithin_iff
#print axioms TrustWeave.haltsWithin_zero
#print axioms TrustWeave.haltPolicy_equiv_deny_iff
#print axioms TrustWeave.policy_equivalence_undecidable
#print axioms TrustWeave.haltPolicy_card_cells_eq_one_iff
#print axioms TrustWeave.haltPolicy_card_cells_eq_two_iff

-- Counterexamples
#print axioms TrustWeave.semantic_mutants_iff_fails_with_one_decision
#print axioms TrustWeave.semantic_mutants_necessity_fails_without_consistency
#print axioms TrustWeave.semantic_mutants_sufficiency_fails_without_consistency
#print axioms TrustWeave.dominance_reading_fails_without_separator

open Lean Elab Command in
/-- Fail unless every theorem in the `TrustWeave` namespace depends only on `propext`,
`Classical.choice` and `Quot.sound`. Reports how many theorems it checked, and how many of
those are declared in the source rather than generated by Lean. -/
elab "#assert_trustweave_axioms" : command => do
  let env ← getEnv
  let allowed : List Name := [``propext, ``Classical.choice, ``Quot.sound]
  let names := env.constants.fold (init := #[]) fun acc n ci =>
    if (`TrustWeave).isPrefixOf n && ci matches .thmInfo _ then acc.push n else acc
  let mut declared : Nat := 0
  for n in names do
    for a in ← liftCoreM <| collectAxioms n do
      unless allowed.contains a do
        throwError "{n} depends on the non-standard axiom {a}"
    if !n.isInternal && (← liftCoreM <| findDeclarationRanges? n).isSome then
      declared := declared + 1
  logInfo m!"{names.size} theorems in namespace TrustWeave ({declared} declared in the \
    source) depend on no axioms beyond propext, Classical.choice and Quot.sound"

#assert_trustweave_axioms
